# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
# Run with:
# bundle exec jekyll serve
#

# Site settings
title: seqfx
email: hi.seqfx@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Experimental software programming development projects for iOS and web.
  Focus on visual data presentation.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://seqfx.com" # the base hostname & protocol for your site
twitter_username:
github_username:  seqfx

# Build settings
markdown: kramdown
